
development:
  adapter: postgresql
  encoding: unicode
  database: blabber_development
  pool: 5
  username: blabber
  password: 

test:
  adapter: postgresql
  encoding: unicode
  database: blabber_test
  pool: 5
  username: blabber
  password:
